#!/usr/bin/env python3
"""自动维护 Hugo 分区 _index.md。

在构建期（见 .ci/guard.sh）与本地（make serve / make build）调用。

对 content/ 下每一个「含 .md 文件的目录」，若缺少 _index.md 则自动创建，
使 cascaded `categories` 始终正确——这正是 /categories/<分区>/ 归档页
与 .ci/check_frontmatter.py 所依赖的。已存在的 _index.md 一律不动，
因此手工定制的（如 AIO 的 title: 自建）会被保留。

生成的文件带 AUTO-GENERATED 标记；若其所属分区已被删除（Enveloppe
autoclean 清理后），对应的孤儿 _index.md 会被自动回收。
"""
import os
import sys

CONTENT = "content"
MARKER = "AUTO-GENERATED by .ci/gen-index.py"


def md_bearing_dirs(root):
    """返回 root 下所有「直接包含 .md 文件」的目录（递归收集）。"""
    out = []
    for dp, _dirnames, filenames in os.walk(root):
        if any(f.endswith(".md") for f in filenames):
            out.append(dp)
    return out


def has_index(d):
    return os.path.isfile(os.path.join(d, "_index.md"))


def is_generated(d):
    p = os.path.join(d, "_index.md")
    try:
        with open(p, encoding="utf-8") as fh:
            return MARKER in fh.read()
    except OSError:
        return False


def create_index(d):
    name = os.path.basename(d)
    path = os.path.join(d, "_index.md")
    text = (
        "---\n"
        f"# {MARKER}\n"
        f'title: "{name}"\n'
        "index: true\n"
        "cascade:\n"
        f'  categories: ["{name}"]\n'
        "---\n"
    )
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(text)
    print(f"gen-index: created {os.path.relpath(path, CONTENT)} (section={name})")


def cleanup_orphans(root, live_dirs):
    """回收：父目录已不复存在（或无 .md）的自动生成 _index.md。"""
    live = set(live_dirs)
    for dp, _dirnames, filenames in os.walk(root):
        if "_index.md" in filenames and is_generated(dp) and dp not in live:
            full = os.path.join(dp, "_index.md")
            try:
                os.remove(full)
                print(f"gen-index: removed orphan {os.path.relpath(full, CONTENT)}")
            except OSError as e:
                print(f"gen-index: WARN cannot remove {full}: {e}", file=sys.stderr)


def main():
    if not os.path.isdir(CONTENT):
        print("gen-index: no content/ dir, skip")
        return
    dirs = [d for d in md_bearing_dirs(CONTENT) if d != CONTENT]
    created = 0
    for d in dirs:
        if has_index(d):
            continue
        create_index(d)
        created += 1
    cleanup_orphans(CONTENT, dirs)
    print(f"gen-index: done (sections={len(dirs)}, created={created})")


if __name__ == "__main__":
    main()
